pipeline {
    agent any
    
    environment {
        PATH = "/Users/gagannagu/.nvm/versions/node/v22.13.1/bin:/opt/homebrew/bin:${env.PATH}"
    }

    triggers {
        githubPush()
        pollSCM('*/2 * * * *')
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }
        
        stage('Cypress Run') {
            steps {
                dir('Test') {
                    // Run Cypress headless execution
                    sh 'npx cypress run --spec cypress_test.cy.js'
                }
            }
        }
    }
}
