pipeline {
    agent any

    environment {
        JAVA_HOME = "/opt/homebrew/Cellar/openjdk/25.0.2/libexec/openjdk.jdk/Contents/Home"
        PATH = "${JAVA_HOME}/bin:/opt/homebrew/bin:${env.PATH}"
    }

    triggers {
        githubPush()
        pollSCM('*/2 * * * *')
    }

    stages {
        stage('Checkout') {
            steps {
                // SCM checkout is automatic in multibranch/pipeline jobs
                echo 'Checking out source code...'
            }
        }
        
        stage('Build & Test') {
            steps {
                dir('selenium-java') {
                    sh 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            // Publish TestNG results to populate the TestNG Reports Analyzer dashboard in Jenkins
            testNG()
        }
    }
}
